<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mrs_action</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="bunin.matthew@gmail.com">matbi</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>action_msgs</depend>
  <depend>mrs_msgs</depend>
  <depend>mrs_action_msgs</depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <test_depend>ament_cmake_ros</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>


